/**
 * Emits encoding vectors from the TypeScript/JS packer so Solidity can assert
 * byte-for-byte agreement. Run: node packages/sdk/generate-vectors.mjs
 *
 * The vectors are produced by the SAME code the frontend uses. Hand-writing
 * them here would defeat the purpose — the test would then only prove Solidity
 * agrees with a transcription, not with the packer that actually ships.
 */
import { writeFileSync } from "node:fs";
import { buildPolicy, buildPolicyWithPC, proofFromIdkitResult } from "./takerArgs.mjs";

// Shaped exactly like a real IDKit v4 result, with values chosen to exercise
// byte boundaries (max-width nullifier, small nonce, non-round expiry).
const idkitResult = {
  protocol_version: "4.0",
  nonce: "0x00d8df4f8cf01c2c27e74f922ee17dcc747ff80407a825692e096e44c2826c2a",
  responses: [
    {
      identifier: "proof_of_human",
      issuer_schema_id: 1,
      expires_at_min: 1784973549,
      nullifier: "0x26efd602e274376068fddd99992d32c5793ca2cc859dc6e4bc06336297eb60d5",
      signal_hash: "0x00e9707d0e6171f728f7473c24cc0432a9b07eaaf1efed6a137a4a8c12c79552",
      proof: [
        "0x46f5615d181dfc8bc4cec2ad7056886057840d5b776fc426ddf32aa442f80a27",
        "0x1b4325b7c6e1a0332360d8fd57806b52a5ac1f8cff6797349a47bb5410e7f057",
        "0x08186533d1b509fca6691b944c5adab4957c604ab17b8f05e3323397cec07cd5",
        "0x3dd66df471c8ac455b5fd887226cbbe396fa97c9e021e7ce95774f677ec657be",
        "0x02d0d8695402907ddbe34ac8969704a4d3fcd801c0d5cf9dc3f15dd9d05d32c0",
      ],
    },
  ],
};

const vectors = {
  _comment: "GENERATED by packages/sdk/generate-vectors.mjs — do not hand-edit.",
  proofArgs: proofFromIdkitResult(idkitResult),
  policy: buildPolicy({ issuerSchemaId: 1, credentialGenesisIssuedAtMin: 0n }),
  policyWithPC: buildPolicyWithPC({ jumpPC: 54, issuerSchemaId: 1, credentialGenesisIssuedAtMin: 0n }),
  inputs: {
    nullifier: idkitResult.responses[0].nullifier,
    nonce: idkitResult.nonce,
    expiresAtMin: idkitResult.responses[0].expires_at_min,
    proof: idkitResult.responses[0].proof,
    issuerSchemaId: 1,
    credentialGenesisIssuedAtMin: 0,
    jumpPC: 54,
  },
};

writeFileSync("test/fixtures/encoding-vectors.json", JSON.stringify(vectors, null, 2) + "\n");
console.log("proofArgs    ", vectors.proofArgs.length - 2, "hex chars =", (vectors.proofArgs.length - 2) / 2, "bytes");
console.log("policy       ", (vectors.policy.length - 2) / 2, "bytes");
console.log("policyWithPC ", (vectors.policyWithPC.length - 2) / 2, "bytes");
